backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "gallery"
    label: "Galeria"
    folder: "src/pages/galeria"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
      - {label: "Nazwa folderu", name: "title", widget: "string"}
      - {label: "Ikona folderu", name: "iconImage", widget: image}
      - {label: "Napis folderu", name: "titleImage", widget: image}
      - {label: "Zdjęcia", name: "galleryImages", widget: list,  fields: [{label: Image, name: image, widget: image}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
